---
environment: production
chdir: /home/registry/EnginesSystemRegistry/
address: 0.0.0.0
port: 4567
pid: /engines/var/run/registry.pid
log: /var/log/thin.log
max_conns: 6
timeout: 30
max_persistent_conns: 6
daemonize: false
